### ISSUE TITLE
How is 'must-build' taken into consideration inside the function 'create_model'

### ISSUE THREAD

**Issue by samuelduchesne** [tum-ens/dhmin#1]
First of all, kudos to this very efficient and well-managed model 😃. I enjoyed creating a simple model for a small neighborhood in my hometown in 🇨🇦.

I have a **question/comment**: I understand that the model should allow to force some segments to be built, instead of letting the solver decide. Although I don't seem to understand where this is applied. Nowhere in the 'create_model' function do I see any mention of the property 'must_build' taken from reading the shapefile. Only 'pipe_exist' is taken into consideration (which forces the pipe to its cap_max). Any thoughts ?

**Comment by ojdo** [comment]
Oh, thank you for your interest in this model. And special thanks for noticing this bug 😳 

Background: this model used to be implemented in another language (GAMS w/ MATLAB for data handling), with identical input file format. When converting to Pyomo, I had stopped adding features once I had everything I needed for my research at the time.

I will add the missing constraint later this month.
